Refactor travis file
canonical/ubuntu-advantage-client pull request #1196
Opened 2020-10-07 14:06 UTC by lucasmoura

Create scripts to reuse on similar integration tests scenarios on travis yaml

2020-10-07 18:32 UTC, blackboxsw requested changes
Let's move these scripts into the existing ./tools  subdir as we may at somepoint what to use and package a ./bin directory  in the deb package. I don't want to confuse tooling with releasable content..

2020-10-07 18:35 UTC, blackboxsw commented on bin/base_travis_integration_tests.sh
> +copy_deb_packages
How we have side-effect functions being called just by sourcing this directory. I'd like to see all explicit call-sites in the scripts which source it. So we are not suprised by hidden behavior

2020-10-07 18:39 UTC, lucasmoura commented
@blackboxsw updated

2020-10-08 16:04 UTC, blackboxsw approved these changes
This looks much cleaner thank you.

2020-10-08 16:04 UTC, merged