Install fips metapacking when enabling service
canonical/ubuntu-advantage-client pull request #1226
Opened 2020-10-28 14:02 UTC by lucasmoura

Currently, we our fips service is expected to install a range of packages that represent the `FIPS`  service. However, we are now expecting `FIPS`  to provide a single metapackage which will install all of the necessary `FIPS` packages for us. To test this feature, we are using the staging contract environment, since the contract in production is still not updated to use the `FIPS` metapackage.

Also, the BDD test for fips are performed only for bionic at this moment. On xenial. when we install the `FIPS` kernel and reboot the machine we cannot access it anymore through `lxd`. That is because the `FIPS` kernel on xenial is missing the required modules to run the `lxd-agent` component of `lxd`, which allow us to communicate with the vm. As a temporary solution, we are testing `FIPS` on xenial through a manual test.

Finally, this PR also fixes #1221, since the error was being caused when we stopped the vm to add new information to the profile. Since this behaviour has been [fixed](https://github.com/lxc/lxd/issues/7648) on lxd, we no longer need this code.

2020-10-28 21:28 UTC, blackboxsw commented on features/staging_commands.feature
> +        When I reboot the `<release>` machine
Let's check that apt update is happy before we reboot
```suggestion
        And I verify that running `apt update` `with sudo` exits `0`            
        When I reboot the `<release>` machine
```

2020-10-29 02:11 UTC, blackboxsw requested changes
One significant thing we are missing in this branch is support for existing Ubuntu PRO FIPS images which we know have a number of versioned packages pinned via `apt-mark hold` calls.
I can't decide if we want to address this in this PR or a followup, but what this represents I believe is a UA client at the moment which will break existing Ubuntu PRO FIPS images on upgrade. 

The reason this will break existing Ubuntu PRO FIPS images is because there are currently newer packages in the real FIPS PPA than were originally pinned in the AWS PRO FIPS image. This will lead to the newer ubuntu-fips metapackage  requiring specific versions of dependencies that will not be installable  and will result in a broken system.


So, we can discuss either:
   1. addressing the apt-mark unhold logic in a separate PR, making sure to add an integration test for AWS (and Azure) Ubuntu PRO images .  Also ensuring not to leak this commit into our release-25 branch in case CPC ends up rolling a new Ubuntu PRO FIPS image in the meantime.

OR 
    2. address the upgrade path on AWS/Azure PRO and add an integration test for that upgrade path to this commit.

I recognize we don't have much in the way of alternative suggestions from the team about how best to handle the `apt-mark holds` on existing FIPS PRO images, but maybe we can meet on this tomorrow to discuss a workable solution.

2020-10-29 13:28 UTC, lucasmoura commented
@blackboxsw I think we can have this work in a separate PR. The reason is we still need to decide how we are gonna install the `FIPS` metapackage in the upgrade scenario on the `FIPS PRO` machines. But I definitely agree that we can discuss this as soon as possible to reach a working solution

2020-10-29 14:42 UTC, lucasmoura commented
@blackboxsw Code updated

2020-10-29 19:03 UTC, blackboxsw approved these changes
+1 looks excellent. Let's wrap up the support of ubuntu-fips metapkg install on existing FIPS PRO machines as separate PRs.

2020-10-29 20:38 UTC, merged