Override fips metapackage when on bionic cloud
canonical/ubuntu-advantage-client pull request #1330
Opened 2021-01-26 21:47 UTC by lucasmoura

Currently, the contract backend will always return the ubuntu-fips metapackage as the package to be installed when we enable fips.
However, we have specific metapackages for Bionic Azure and AWS instances, called ubuntu-aws-fips and ubuntu-azure-fips. Until we do not support that on the contracts backend, we will be performing this override directly on the uaclient code

2021-01-27 17:46 UTC, blackboxsw commented on uaclient/entitlements/tests/test_fips.py
> +    @pytest.mark.parametrize("cloud_id", (("Azure"), ("AWS"), ("GCE"), (None)))
These values returens from get_cloud_type are all lowercase "aws", "gce" "azure" etc.

2021-01-27 17:49 UTC, blackboxsw commented on uaclient/entitlements/fips.py
> +        if cloud_id and cloud_id.lower() in ("azure", "aws"):
Forgot to mention in previous PR on livepatch/fips incompatible_services branch. get_cloud_type() always returns either None or lowercase strings to no need to `lower()` it here.
```suggestion
        if cloud_id and cloud_id in ("azure", "aws"):
```


We could drop that cloud_id.lower() call in _prevent_fips_on_xenial_cloud_instances too

2021-01-27 17:50 UTC, blackboxsw requested changes
minor needs fixing

2021-01-27 19:29 UTC, ubuntu-server-builder approved these changes
LGTM! Let's land it when CI passes

2021-01-27 19:30 UTC, blackboxsw approved these changes
LGTM! Let's merge it when CI passes here.

2021-01-27 20:52 UTC, blackboxsw requested changes
I have a second thoughts to discuss:

1. should we not even call super().packages if we are on bionic/aws|azure?
2. should we provide a config override to allow addtionalPackages contract directive in some cases? (A config option to disable overrides to additionalPackages would allow us some wiggle room if additionalPackages does update to something that includes a different metapackage than just ubuntu-aws-fips etc).

If we wanted both of those something like the following could work:
```diff
diff --git a/uaclient/entitlements/fips.py b/uaclient/entitlements/fips.py
index e32e50d..87191fa 100644
--- a/uaclient/entitlements/fips.py
+++ b/uaclient/entitlements/fips.py
@@ -87,33 +87,44 @@ class FIPSCommonEntitlement(repo.RepoEntitlement):
             ),
         )
 
-    def _replace_metapackage_on_cloud_instance(
-        self, packages: "List[str]"
-    ) -> "List[str]":
+    def _get_package_overrides_on_cloud(self) -> "List[str]":
         """
-        Identify correct metapackage to be used if in a cloud instance.
+        Identify FIPS metapackage overrides when needed on a cloud instance.
 
         Currently, the contract backend is not delivering the right
         metapackage on a Bionic Azure or AWS cloud instance. For those
         clouds, we have cloud specific fips metapackages and we should
         use them. We are now performing that correction here, but this
         is a temporary fix.
+
+        :return: Empty list whe no overrides preferred, non-empty list when
+            override is required.
         """
+        no_package_overrides = []
+        cfg_allow_bionic_cloud_packages = util.is_config_value_true(
+            config=self.cfg.cfg,
+            path_to_value="features.allow_bionic_fips_packages_on_cloud",
+        )
+        if cfg_allow_bionic_cloud_packages:
+            return no_package_overrides
+
         series = util.get_platform_info().get("series")
 
         if series != "bionic":
-            return packages
+            return no_package_overrides
 
         cloud_id = get_cloud_type()
         if cloud_id and cloud_id in ("azure", "aws"):
             return ["ubuntu-{}-fips".format(cloud_id)]
 
-        return packages
+        return no_package_overrides
 
     @property
     def packages(self) -> "List[str]":
+        package_overrides = self._get_package_overrides_on_cloud()
+        if package_overrides:
+            return package_overrides
         packages = super().packages
-        packages = self._replace_metapackage_on_cloud_instance(packages)
         installed_packages = apt.get_installed_packages()
 
         pkg_groups = groupby(
```

2021-01-28 00:38 UTC, blackboxsw requested changes
Looks more flexible thanks. One thing I think we should do is make this for loop a bit more pythonic by using a list comprehension
```diff
diff --git a/uaclient/entitlements/fips.py b/uaclient/entitlements/fips.py
index 800bce9..1d1cdbc 100644
--- a/uaclient/entitlements/fips.py
+++ b/uaclient/entitlements/fips.py
@@ -1,5 +1,3 @@
-import copy
-
 from itertools import groupby
 
 from uaclient import apt
@@ -113,18 +111,14 @@ class FIPSCommonEntitlement(repo.RepoEntitlement):
         if series != "bionic":
             return packages
 
-        override_packages = copy.copy(packages)
-
-        for index, package in enumerate(packages):
-            if package == "ubuntu-fips":
-                cloud_id = get_cloud_type()
-                if cloud_id and cloud_id in ("azure", "aws"):
-                    override_packages[index] = "ubuntu-{}-fips".format(
-                        cloud_id
-                    )
-                    break
-
-        return override_packages
+        cloud_id = get_cloud_type()
+        if not cloud_id or cloud_id not in ("azure", "aws"):
+            return packages
+        cloud_metapkg = "ubuntu-{}-fips".format(cloud_id)
+        # Replace only the ubuntu-fips meta package if exists
+        return [
+            cloud_metapkg if pkg == "ubuntu-fips" else pkg for pkg in packages
+        ]
 
     @property
     def packages(self) -> "List[str]":
csmith@uptown:~/src/ubuntu-advantage-client$ git diff
diff --git a/uaclient/entitlements/fips.py b/uaclient/entitlements/fips.py
index 800bce9..1d1cdbc 100644
--- a/uaclient/entitlements/fips.py
+++ b/uaclient/entitlements/fips.py
@@ -1,5 +1,3 @@
-import copy
-
 from itertools import groupby
 
 from uaclient import apt
@@ -113,18 +111,14 @@ class FIPSCommonEntitlement(repo.RepoEntitlement):
         if series != "bionic":
             return packages
 
-        override_packages = copy.copy(packages)
-
-        for index, package in enumerate(packages):
-            if package == "ubuntu-fips":
-                cloud_id = get_cloud_type()
-                if cloud_id and cloud_id in ("azure", "aws"):
-                    override_packages[index] = "ubuntu-{}-fips".format(
-                        cloud_id
-                    )
-                    break
-
-        return override_packages
+        cloud_id = get_cloud_type()
+        if not cloud_id or cloud_id not in ("azure", "aws"):
+            return packages
+        cloud_metapkg = "ubuntu-{}-fips".format(cloud_id)
+        # Replace only the ubuntu-fips meta package if exists
+        return [
+            cloud_metapkg if pkg == "ubuntu-fips" else pkg for pkg in packages
+        ]
 
     @property
     def packages(self) -> "List[str]":
```

2021-01-28 15:29 UTC, ubuntu-server-builder approved these changes

2021-01-28 15:30 UTC, blackboxsw approved these changes
LGTM

2021-01-28 15:31 UTC, merged