[WIP] Update pycloudlib
canonical/ubuntu-advantage-client pull request #1370
Opened 2021-02-12 13:23 UTC by lucasmoura

## Proposed Commit Message
Make lxd containers execute commands by ssh

## Test Steps
Currently, we are only using ssh to execute commands on lxd virtual machines. With recent modifications on pycloudlib, lxd instances are using ssh by default. We are now migrating our lxd containers to execute commands by ssh too.

Also, pycloudlib now handles the profile creation of lxd virtual machines. Therefore, we don't need to support that code on uaclient anymore

PS: We are still waiting on this pycloudlib [PR](https://github.com/canonical/pycloudlib/pull/117) to land, so we can bump the pycloudlib version we are using in the project

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-02-18 16:14 UTC, blackboxsw requested changes
I think we should be tweaking integration-requirements.txt and grabbing the latest commit in pycloudlib now that your lxc-setup.sh has landed.

2021-02-18 18:12 UTC, lucasmoura commented
@blackboxsw Updated to use the latest version of pycloudlib

2021-02-18 23:58 UTC, blackboxsw reviewed
While this drop looks good because this is in pycloudlib proper, I think we might end up rejecting this after a conversation on this tomorrow because pycloudlib might eject that functionality and let uaclient integration tests carry that burden.

2021-02-23 20:14 UTC, blackboxsw approved these changes
LGTM as that CI failure seems intermittent on 14.04. We will double check next CI runs to determine frequency of this error and address it if it shows up.

2021-02-23 20:16 UTC, merged