status: do not show info if not on contract
canonical/ubuntu-advantage-client pull request #1597
Opened 2021-04-29 14:32 UTC by lucasmoura

## Proposed Commit Message
status: do not show info if not on contract

When running status on an attached machine, we present the account and subscription info in the the end. However, if the contract does not have that info, we will present them as empty. We are now updating the status to not show that info at the end if it is not present in the contract.

Fixes: #1592

## Test Steps
Run the modified unittests

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-04-29 14:43 UTC, blackboxsw requested changes
Redacting looks good, but shouldn't this branch also touch on 
addressing the fact that contract_name is empty and we still emit
[MESSAGE_ATTACH_SUCCESS_TMPL](https://github.com/canonical/ubuntu-advantage-client/blob/main/uaclient/cli.py#L683)

2021-04-29 14:43 UTC, cpaelzer commented
From just looking at the changes that LGTM non authoritative +0.5

2021-04-29 15:03 UTC, orndorffgrant approved these changes
This looks good and worked for me!

2021-04-30 02:14 UTC, blackboxsw approved these changes
LGTM!

2021-05-03 22:12 UTC, merged