cis: make service non-beta
canonical/ubuntu-advantage-client pull request #1644
Opened 2021-05-19 21:01 UTC by lucasmoura

## Proposed Commit Message
cis: make service non-beta

Turn CIS into a non-beta service and update the integration test to run the CIS script on the machine

## Test Steps
Run the modified integration tests

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-05-19 21:27 UTC, orndorffgrant reviewed
Just did a quick lookover and it looks great! I'll look again more in depth tomorrow

2021-05-20 00:35 UTC, blackboxsw commented on features/attached_enable.feature
> +        And I verify that running `/usr/share/ubuntu-scap-security-guides/cis-hardening/<cis_script> lvl1_workstation` `with sudo` exits `0`
Lets add a check before hardening:
  And I run `cis-audit level1_server` with sudo
  Then stdout matches regexp
   """
   Title   Ensure root PATH Integrity
   Rule    xccdf_com.ubuntu.xenial.cis_rule_CIS-6.2.6
   Result  pass
   """
   And stdout matches regexp:
    """
   Title   Ensure password expiration is 90 days or less
   Rule    xccdf_com.ubuntu.xenial.cis_rule_CIS-5.4.1.1
   Result  fail
   """

 Might be worth adding also a stdout check re-running cis-audit after your cis-hardening script to ensure that the one "failed" case you audited for was fixed by the harden script

2021-05-20 00:36 UTC, blackboxsw requested changes
Let's also add a test for use of cis-audit too. and maybe a post harden retest on cis-audit to see that it fixed a failed case.

2021-05-20 14:41 UTC, lucasmoura commented
@blackboxsw Great call here. I have updated the code to add the `cis-audit` checks

2021-05-21 15:24 UTC, blackboxsw approved these changes
LGTM!

2021-05-21 15:24 UTC, merged