status: add account info into json output
canonical/ubuntu-advantage-client pull request #1695
Opened 2021-06-28 20:23 UTC by lucasmoura

## Proposed Commit Message
status: add account info into json output

We are now creating a separate account object in the status json output. We are moving all account related info into that object while also adding new fields to into, such as created_at

## Test Steps
Launch a PRO instance and check that the account info we are adding appears when running `ua status --format json`

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-06-29 20:48 UTC, lucasmoura commented
@orndorffgrant Code updated with the same refactoring proposed on the `contracts` PR

2021-06-30 03:12 UTC, blackboxsw requested changes
With these types of changes where we are changing the structure of the status.json on disk, We need to probably trigger a re-write of status.json across upgrade path. Otherwise non-root users on an already attached machine will hit stuff like this if they run `ua status` and the new-code doesn't know how to handle the old keys on disk. We have the same type of upgrade path problem in cloud-init,

```bash
ubuntu@dev-x:~$ ua --debug status
DEBUG: Executed with sys.argv: ['/usr/bin/ua', '--debug', 'status']
DEBUG: Reading file: /var/lib/ubuntu-advantage/status.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/notices.json
DEBUG: File does not exist: /var/lib/ubuntu-advantage/notices.json
ERROR: Unhandled exception, please file a bug
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 976, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 1049, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 876, in action_status
    output = ua_status.format_tabular(status)
  File "/usr/lib/python3/dist-packages/uaclient/status.py", line 614, in format_tabular
    tech_support_level = status["contract"]["tech_support_level"]
KeyError: 'contract'
Unexpected error(s) occurred.
For more details, see the log: /var/log/ubuntu-advantage.log
To file a bug run: ubuntu-bug ubuntu-advantage-tools
```

2021-06-30 13:40 UTC, lucasmoura commented
@blackboxsw Great catch.

I think the optimal solution would be to update the `status.json` file during `postinst`. However,  if we do that we may affect the execution of `upgrade_lts_contract` since it checks `status.json` directly to assert if a service was enable. Therefore, we cannot touch it there.

I think we have some solutions that we can implement here:

1) Support both `status.json` outputs when constructing status output
2) Do not display info in the `status.json` output if we can't find that info. Maybe we could also emit a notice for this situation asking the user to run the command as root.

But if you or @orndorffgrant have any other ideas for that, let me know and we can better discuss a path moving forward here

2021-07-01 20:01 UTC, orndorffgrant approved these changes
LGTM! And the migration from old status.json will happen in a later PR

2021-07-01 21:42 UTC, blackboxsw approved these changes
LGTM! yes later PR will tackle status schema upgrade issues.

2021-07-01 21:42 UTC, merged