Integration tests upgrade unattached
canonical/ubuntu-advantage-client pull request #1742
Opened 2021-07-20 17:40 UTC by lucasmoura

This PR is based on #1738, only dropping the cis check on the integration test were we upgrade from focal into groovy

2021-07-20 17:45 UTC, renanrodrigo approved these changes
lgtm

2021-07-20 17:47 UTC, orndorffgrant commented on features/ubuntu_upgrade.feature
> +        And I run `do-release-upgrade <devel_release> --frontend DistUpgradeViewNonInteractive` `with sudo` and stdin `y\n`
It looks like this is supposed to use the `stdin` var from the examples?

```suggestion
        And I run `do-release-upgrade <devel_release> --frontend DistUpgradeViewNonInteractive` `with sudo` and stdin `<stdin>`
```

2021-07-20 17:47 UTC, orndorffgrant commented on features/ubuntu_upgrade.feature
> +        And I run `do-release-upgrade <devel_release> --frontend DistUpgradeViewNonInteractive` `with sudo` and stdin `y\n`
Or should we leave `y/n` hardcoded here and remove the `stdin` column in the examples?

2021-07-20 19:21 UTC, orndorffgrant requested changes
Looks like we can't just delete the cis line. Instead we'll have to specify it is not available.

```
    When I run `ua status` with sudo                                                                                    # features/steps/steps.py:177 0.870s
    Then stdout matches regexp                                                                                          # features/steps/steps.py:361 0.001s
      """
      SERVICE       AVAILABLE  DESCRIPTION
      esm-infra     no       +UA Infra: Extended Security Maintenance \(ESM\)
      """
      Assertion Failed: 
      Expected: a string matching 'SERVICE       AVAILABLE  DESCRIPTION
      esm-infra     no       +UA Infra: Extended Security Maintenance \(ESM\)'
           but: was 'SERVICE       AVAILABLE  DESCRIPTION\ncis           no         Center for Internet Security Audit Tools\nesm-infra     no         UA Infra: Extended Security Maintenance (ESM)\nfips          no         NIST-certified core packages\nfips-updates  no         NIST-certified core packages with priority security updates\nlivepatch     no         Canonical Livepatch service\n\nThis machine is not attached to a UA subscription.\nSee https://ubuntu.com/advantage'
```

2021-07-21 14:01 UTC, lucasmoura commented
@orndorffgrant what is the package version you are seeing on `groovy` ?

2021-07-21 14:28 UTC, orndorffgrant commented
@lucasmoura I believe that error was from running `tox -e behave-upgrade-21.04` so no groovy involved.

Maybe we should only check for the esm-infra line, instead of both the header and esm-infra line?

Like this
```diff
        Then stdout matches regexp:
        """
-       SERVICE       AVAILABLE  DESCRIPTION
        esm-infra     no       +UA Infra: Extended Security Maintenance \(ESM\)
        """
```

2021-07-21 17:19 UTC, lucasmoura commented
@orndorffgrant PR updated

2021-07-21 21:00 UTC, orndorffgrant approved these changes
Sorry for the delay, I ran all the upgrade tests to make sure they were all working. Looks great!

2021-07-21 21:00 UTC, orndorffgrant commented
The integration test failure on jenkins is unrelated to these changes.

2021-07-21 21:00 UTC, merged