fix: do not fail if non-utf8 locale is being used (SC-368)
canonical/ubuntu-advantage-client pull request #1776
Opened 2021-08-25 20:23 UTC by lucasmoura

## Proposed Commit Message
When running an ua fix command, we tell at the end if the issue is resolved or not. In that message, we have some unicode characters that are displayed. If the user is running on a system that doesn't support those characters, the printing that last message will fail. We are now redacting the code to not fail under this condition.

Fixes: #1463

## Test Steps
Run the new unittest provided in the system.
Another way to test is to launch an instance and change the locale to `ANSI_X3.4-1968`. Run an ua fix command and verify that it doesn't break on the message

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [x] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-08-30 12:27 UTC, renanrodrigo requested changes

2021-08-30 12:27 UTC, renanrodrigo commented on uaclient/status.py
> +MESSAGE_SECURITY_ISSUE_NOT_RESOLVED_NON_UTF8 = "{issue} is not resolved."
Now that we have the function, those are not needed anymore

2021-08-30 13:09 UTC, lucasmoura commented
@renanrodrigo code updated

2021-08-30 13:45 UTC, blackboxsw approved these changes
Two minor unrelated changes which I think can be dropped. Otherwise +1 and ship it.

2021-08-30 13:49 UTC, renanrodrigo commented
CI complains about some other unittests failing - worth a check

2021-08-30 14:37 UTC, lucasmoura commented on uaclient/tests/test_security.py
> +    MESSAGE_SECURITY_ISSUE_NOT_RESOLVED,
It was just because in the older implementation I had other status messages here. But I will remove that reorder

2021-08-30 19:33 UTC, blackboxsw commented on uaclient/tests/test_security.py
> +                    return_value="utf-8"
Now I finally discern what mock @renanrodrigo was talking about. Didn't realize you were talking about this PR earlier. +1

2021-08-30 19:35 UTC, blackboxsw approved these changes
LGTM. Awaiting CI

2021-08-30 19:48 UTC, blackboxsw commented
CI failure w/ lxc launch on focal (unrelated to this PR)       RuntimeError: Failure (rc=1): Error: Failed getting disk path: Could not locate a zvol for default/virtual-machines/ubuntu-behave-test-1776-vm-focal-1630349395863675.block

2021-08-30 19:52 UTC, renanrodrigo approved these changes

2021-08-31 02:37 UTC, blackboxsw approved these changes
Integration test lockup on Xenial. Any integration tests  which would have changed would have affected Bionic and Focal test cases too. So, I'm +1 with this changeset as unittest coverage covers the differing behavior in odd cases when LANG is not yet set, or unset intentionally by an image.

2021-08-31 02:38 UTC, merged