ros: unhide ros entitlements
canonical/ubuntu-advantage-client pull request #1805
Opened 2021-09-15 14:29 UTC by orndorffgrant

## Notes

There is movement on the ticket to update the ros infrastructure. We need to be ready to test on staging and give the go ahead for moving to production and then release this asap.

## Proposed Commit Message

```
ros: unhide ros entitlements
```

## Test Steps

Enable ros: verify it auto enables esm infra and apps

enable ros-updates: verify it auto enables esm infra and apps and ros

## Desired commit type::

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [x] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist:

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-09-17 11:45 UTC, renanrodrigo commented
When enabling ROS, we could also update the README / manpage, so docs are up-to-date. I think this PR would be a good place to do so.

2021-09-17 12:25 UTC, orndorffgrant commented
@renanrodrigo absolutely! good catch

2021-09-17 13:47 UTC, orndorffgrant commented
ROS is working! This is ready for review

2021-09-17 17:43 UTC, lucasmoura approved these changes

2021-09-17 17:48 UTC, blackboxsw commented on uaclient/tests/test_cli_status.py
> +BETA_SVC_NAMES = ["cc-eal", "esm-apps", "ros", "ros-updates"]
Why are we claiming ros and ros-updates are beta? Wouldn't this be the time we drop the is_beta = True definition and just make this a fully participating service?

2021-09-17 17:49 UTC, blackboxsw requested changes
@orndorffgrant don't we actually want to drop the is_beta definition on ROS and ROS-updates in this branch? I *think* it looks like the service and applicable debs can be installed without error right?

2021-09-17 17:51 UTC, orndorffgrant commented
@blackboxsw We could go straight from not-existing -> non-beta if it weren't for the fact that ros requires esm-apps to be enabled, which is still beta. I think it would be un-intuitive for a non-beta service to require enabling a beta service. I'm open to arguments otherwise though

2021-09-17 18:25 UTC, blackboxsw commented
> @blackboxsw We could go straight from not-existing -> non-beta if it weren't for the fact that ros requires esm-apps to be enabled, which is still beta. I think it would be un-intuitive for a non-beta service to require enabling a beta service. I'm open to arguments otherwise though

Thanks, forgot about that. Agreed that it would be a surprise to have a beta service enabled when enabling ROS/ROS-updates. We'll sort expectations with Lech on this given other esm-apps discussions that are in flight.

2021-09-17 18:25 UTC, blackboxsw approved these changes
+1 Release the beta hounds

2021-09-17 18:29 UTC, orndorffgrant commented
Ha ha! :dog2: :dog2: 

Will first fix the couple minor test failures around pro contracts not entitling ros, then I'll go ahead and merge

2021-09-17 18:37 UTC, renanrodrigo approved these changes
late lgtm is lgtm

2021-09-20 13:04 UTC, orndorffgrant commented
There are some test failures as a result of switching tokens, addressing now

2021-09-20 13:46 UTC, lucasmoura approved these changes

2021-09-20 18:26 UTC, orndorffgrant commented
The final set of CI tests passed on my machine. Merging now

2021-09-20 18:26 UTC, merged