fips: update integration tests for focal
canonical/ubuntu-advantage-client pull request #1863
Opened 2021-11-05 19:53 UTC by lucasmoura

## Proposed Commit Message
fips: update integration tests for focal

Initially, there was no strongswan-hmac FIPS package for Focal. Therefore, during the enable operation we state that this package could not be installed. Now that the package can be installed on a Focal machine, we are removing that message from the integration tests

## Test Steps
Run the modified integration tests

## Desired commit type

 - [ ] Squash and merge: Using the "Proposed Commit Message"
 - [ ] Create a merge commit and use "Proposed Commit Message"
 - [ ] Rebase and merge, no merge commit, rely only on existing commit messages

## Checklist

 - [ ] I have updated or added any unit tests accordingly
 - [ ] I have updated or added any integration tests accordingly
 - [ ] I have updated or added any documentation accordingly

2021-11-05 20:07 UTC, renanrodrigo requested changes
Besides removing the lines, I think we need to check that `strongswan-hmac` is being installed from the FIPS source and that after disabling, the fips version keeps installed (like we do for the Xenial/Bionic tests).

2021-11-05 20:13 UTC, lucasmoura commented
@renanrodrigo good catch. I will add that check

2021-11-05 21:26 UTC, lucasmoura commented
@renanrodrigo updated

2021-11-09 19:21 UTC, orndorffgrant approved these changes
This worked for me, thanks!

2021-11-09 20:05 UTC, renanrodrigo approved these changes
LGTM

2021-11-11 14:30 UTC, lucasmoura commented
CI errors are unrelated to this change

2021-11-11 14:30 UTC, merged